---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
keywords:
  - hunspell
  - spelling
  - spell-checker
  - text-processing
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Hunspell
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  repository: https://github.com/cosimo/perl5-text-hunspell
version: 2.07
